server:
  port: 8000

eureka:
  client:
    #client의 역할로 자신의 정보를 자신에게 등록하는 의미없는 현상 방지
    #외부에 있는 다른 마이크로서비스랑 통신 필요 없음
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: coinbuying-gateway

  cloud:

    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 2s
      routes:
        - id: say-hello
          uri: http://localhost:8085
          predicates:
            - Path=/hello/**

